# -*- coding: utf-8 -*-
"""Sisipkan blok explain orisinal ke 30 modul di data.js NihonGo Master.

Sumber konten: ditulis sendiri oleh Muse dari pengetahuan tata bahasa Jepang
umum (bukan salinan situs acuan mana pun). Script idempoten: modul yang sudah
punya explain dilewati.
"""
import re, sys

PATH = "/home/hatch/workspace/belajar-bahasa-jepang/data.js"

EDITS = []

EDITS.append(("n5-particles-core", '''explain:[
  {h:"Kenapa は dibaca \\"wa\\"", p:["Partikel は adalah sisa ejaan kuno: ia ditulis dengan kana は (ha) tetapi dibaca \\"wa\\" saat bekerja sebagai penanda topik. Jadi わたしは dibaca \\"watashi wa\\", bukan \\"watashi ha\\". Hal yang sama terjadi pada partikel へ (dibaca \\"e\\") dan を (dibaca \\"o\\") — ketiganya adalah fosil ejaan lama yang dipertahankan sampai sekarang.", "Topik adalah hal yang sudah diketahui bersama oleh pembicara dan pendengar, semacam judul kalimat: \\"ngomong-ngomong soal X…\\". Karena itu は sering muncul di awal kalimat atau saat memperkenalkan diri."]},
  {h:"は lawan が: informasi lama vs baru", p:["Cara paling mudah membedakannya: は menunjuk hal yang sudah jelas dari konteks (informasi lama), sedangkan が memperkenalkan hal baru atau menyorot pelaku secara khusus. Itulah sebabnya pertanyaan \\"siapa?\\" memakai が (だれが きましたか), dan jawabannya pun membalas dengan が — karena orang itu baru saja disebutkan pertama kali.", "Dalam kalimat negatif, objek yang biasanya ditandai を sering berganti menjadi は: にほんごは わかりません (bahasa Jepang sih, saya tidak paham). Nuansanya menjadi kontras: bagian itu disangkal, tetapi hal lain mungkin tidak."]},
  {h:"を dan tanda objek", p:["Partikel を menempel tepat sesudah kata benda yang dikenai perbuatan: ほんを よむ, ごはんを たべる. Dalam percakapan cepat, orang Jepang sering menghilangkan partikel ini sama sekali (ほん よむ), tetapi dalam tulisan dan ujaran sopan partikel tetap dipakai.", "Satu pengecualian penting: kata kerja gerak seperti あるく dan わたる memakai を untuk tempat yang dilintasi — みちを あるく berarti berjalan menyusuri jalan, bukan \\"memakan jalan\\"."]}
]'''))

EDITS.append(("n5-particles-place", '''explain:[
  {h:"に untuk titik, で untuk panggung", p:["Bayangkan に sebagai pin di peta: ia menandai titik akhir gerakan (がっこうに いく), titik waktu (しちじに おきる), dan titik keberadaan (へやに いる). Di tempat pin itu menancap, tidak ada \\"aksi yang digelar\\" — pin hanya menunjukkan lokasi diam atau tujuan.", "Sebaliknya で adalah panggung tempat aksi berlangsung: としょかんで べんきょうする (belajar yang digelar di perpustakaan), バスで いく (perjalanan yang dilakukan dengan bus). Trik ingatannya: kalau bisa ditanya \\"sedang ngapain di sana?\\", pakailah で; kalau ditanya \\"menuju ke mana / ada di mana?\\", pakailah に."]},
  {h:"へ dan に: arah vs tujuan", p:["へ (dibaca \\"e\\") dan に sama-sama bisa berarti \\"ke\\", tetapi rasanya berbeda. に menekankan titik tiba, sedangkan へ menekankan arah perjalanan — seperti perbedaan \\"sampai di Tokyo\\" dan \\"menuju Tokyo\\". Dalam percakapan sehari-hari keduanya sering tertukar tanpa masalah, tetapi dalam surat dan tulisan formal へ terasa lebih puitis.", "Partikel と punya dua wajah: penghubung daftar yang lengkap (りんごと バナナ — hanya dua itu) dan penanda teman beraktivitas (ともだちと はなす). Untuk daftar yang tidak lengkap, bahasa Jepang memakai や: ほんや ノート (buku, buku catatan, dan sebagainya)."]}
]'''))

EDITS.append(("n5-verbs", '''explain:[
  {h:"Tiga golongan kata kerja", p:["Semua kata kerja Jepang masuk ke salah satu dari tiga golongan. Golongan 2 paling jinak: akhiran る tinggal diganti ます (たべる → たべます, みる → みます). Golongan 1 berubah bunyi: suku kata terakhir naik ke baris -i lalu tambah ます (かく → かきます, のむ → のみます, いく → いきます). Golongan 3 hanya dua kata tidak beraturan: する → します dan くる → きます.", "Cara membedakan golongan 1 dan 2 yang berakhiran る: lihat vokal sebelum る. Jika a, u, atau o, hampir pasti golongan 1 (わかる, つくる). Jika e atau i, biasanya golongan 2 (たべる, みる) — kecuali segelintir penyusup terkenal seperti かえる (pulang) dan はいる (masuk) yang golongan 1."]},
  {h:"Satu akar, empat wajah sopan", p:["Dari akar yang sama lahir empat bentuk dasar: ます (sekarang/nanti), ません (negatif), ました (lampau), ませんでした (lampau negatif). Pertanyaan tinggal menambah か di ujung: いきますか. Bentuk lampau negatif ませんでした sering terasa panjang, sehingga dalam percakapan orang memakainya dengan ritme pelan dan jelas.", "Sedikit jebakan: kata kerja わかる (paham) tidak menerima objek dengan を melainkan が — にほんごが わかります. Pola yang sama berlaku untuk すき, きらい, ほしい, dan bentuk bisa: hal yang dipahami/disukai/dibisa ditandai が."]}
]'''))

EDITS.append(("n5-adjectives", '''explain:[
  {h:"Kata sifat-い berubah seperti kata kerja", p:["Kata sifat-い membawa akhiran い sebagai bagian tubuhnya, sehingga ia bisa berubah sendiri: あつい (panas) → あつくない (tidak panas) → あつかった (dulu panas) → あつくなかった (dulu tidak panas). Triknya: buang い, ganti dengan くない untuk negatif dan かった untuk lampau. Satu kata berkhianat: いい (baik) berubah dari akar よ-: よくない, よかった, bukan いくない.", "Kata sifat-な tidak bisa berubah sendiri; ia meminjam です/だ dan menambahkan な hanya saat menempel di depan kata benda: しずかな へや (kamar yang tenang) tetapi へやは しずかです (kamarnya tenang). Kesalahan pemula yang klasik adalah menulis しずか な です — な tidak pernah berdiri di depan です."]},
  {h:"Derajat dan penekanan", p:["Untuk melebihkan, bahasa Jepang memakai urutan tetap: A より B のほうが (B lebih … daripada A) dan いちばん untuk yang paling. Kata keterangan とても menaikkan derajat (とても あつい, sangat panas), sedangkan あまり selalu berpasangan dengan bentuk negatif: あまり あつくない berarti \\"tidak terlalu panas\\".", "Urutan mempelajari kata sifat yang aman: kuasai dulu bentuk sekarang dan negatifnya, baru lampau. Dalam percakapan sehari-hari bentuk lampau kata sifat muncul terus-menerus, misalnya saat bercerita きのうは さむかった (kemarin dingin)."]}
]'''))

EDITS.append(("n5-daily", '''explain:[
  {h:"Kata tanya dan tempatnya", p:["Kata tanya Jepang berperilaku seperti kata biasa: ia duduk persis di posisi jawaban yang dicari. それは いくらですか dijawab dengan menyebutkan harga menggantikan いくら. Karena itu kalimat tanya tidak perlu dibolak-balik seperti bahasa Inggris — cukup ganti potongan yang ditanyakan dan akhiri dengan か (atau tanpa か dalam gaya akrab dengan intonasi naik).", "何 punya dua bacaan: なん di depan bunyi t, d, n dan penghitung (なんじ, 何ですか dibaca なんですか), serta なに di posisi lain (なにを たべますか). Untuk \\"kapan\\", いつ tidak memakai partikel に: いつ いきますか, bukan いつに."]},
  {h:"Frekuensi: seberapa sering", p:["Kata keterangan frekuensi duduk sebelum kata kerja: まいにち (setiap hari), よく (sering), ときどき (kadang-kadang), あまり + negatif (jarang), ぜんぜん + negatif (sama sekali tidak). Kombinasi あまり dan ぜんぜん wajib berpasangan dengan kalimat negatif — menulis あまり いきます adalah kesalahan yang sering terjadi pada pemula.", "〜たいです menyatakan keinginan melakukan, bukan menginginkan benda: にほんへ いきたいです (ingin pergi), sedangkan benda yang diinginkan memakai 〜が ほしいです: あたらしい くつが ほしいです. Campuran keduanya, 〜を たべたいです, adalah bentuk paling umum untuk makanan."]}
]'''))

EDITS.append(("n4-te", '''explain:[
  {h:"Bentuk て lahir dari akhiran", p:["Bentuk て dibuat dari bentuk kamus dengan aturan eufoni (perubahan bunyi agar mudah diucapkan). Golongan 2 mudah: る hilang diganti て (たべて, みて). Golongan 1 mengikuti pasangan tetap: う・つ・る menjadi って (かって, まって, かえって), む・ぶ・ぬ menjadi んで (のんで, あそんで), く menjadi いて (かいて) kecuali いく yang menjadi いって, ぐ menjadi いで (およいで), dan す menjadi して (はなして).", "Ingat lagu sederhananya: \\"u-tsu-ru → tte; mu-bu-nu → nde; ku → ite; gu → ide; su → shite\\". Sekali pola ini melekat, bentuk た, ない, dan たり di modul berikutnya terasa jauh lebih ringan karena memakai akar yang sama persis."]},
  {h:"Empat pekerjaan utama bentuk て", p:["Pertama, menyambung tindakan berurutan: あさ おきて、シャワーを あびて、でかけます — bangun, mandi, lalu berangkat. Kedua, meminta: まってください. Ketiga, memberi dan menolak izin: たべても いいですか (bolehkah saya makan?) dan ここで たばこを すっては いけません (dilarang merokok di sini). Keempat, keadaan yang sedang berjalan: よんでいます — yang bisa berarti \\"sedang membaca\\" atau \\"sudah membaca dan hasilnya masih berlaku\\", tergantung konteks.", "Pasangan ています/てあります membedakan pelaku: まどが あいています (jendelanya terbuka — keadaannya), まどが あけてあります (jendelanya sudah dibuka orang — ada pelaku yang menyiapkannya). Nuansa kecil ini sering diuji di N4."]}
]'''))

EDITS.append(("n4-dictionary", '''explain:[
  {h:"Satu akar untuk semua bentuk polos", p:["Bentuk kamus, た, dan ない lahir dari akar yang sama. Dalam praktiknya, cukup hafalkan padanan bentuk て: て ↔ た memakai bunyi yang identik — かく → かいて → かいた; のむ → のんで → のんだ. Golongan 2 tinggal menukar る: たべる → たべた → たべない. Golongan 3: する → した → しない, くる → きた → こない.", "Inilah alasan bentuk kamus disebut \\"kunci gudang\\": hampir semua pola N4 ke atas menempel padanya — こと, ため, 前に, あとで, かもしれません. Menguasai konjugasi dasar sekarang menghemat banyak tenaga nanti."]},
  {h:"Apa yang bisa menempel pada bentuk polos", p:["〜たことがある menceritakan pengalaman (にほんに いったことが あります), sedangkan pasangannya yang penting: 〜たことがない berarti \\"belum pernah sama sekali\\", berbeda dari bentuk lampau negatif biasa …ませんでした (tidak melakukannya saat itu).", "Pola 〜ないでください (tolong jangan) berdiri di atas bentuk ない tanpa です: とらないでください. Kakaknya, 〜なければならない (harus), dibahas khusus di N3. Sementara 〜たり〜たり merangkum contoh kegiatan tanpa urutan: よんだり かいたり します — membaca, menulis, dan semacamnya."]}
]'''))

EDITS.append(("n4-conditionals", '''explain:[
  {h:"Empat \\"kalau\\" dengan rasa berbeda", p:["たら adalah kalau serbaguna: ia menempel pada bentuk た dan bekerja untuk urutan waktu maupun hipotesis — あめが ふったら (kalau/setelah hujan turun). Karena serbaguna, たら aman dipakai pemula di hampir semua situasi sehari-hari.", "ば terasa lebih \\"syarat logis\\": やれば できる (kalau dikerjakan, pasti bisa). Ia tidak cocok untuk kejadian lampau yang sudah pasti. と sebaliknya hanya untuk akibat yang selalu/otomatis terjadi — kebenaran umum dan mesin: はるに なると、はなが さきます (kalau musim semi tiba, bunga mekar). Klausa sesudah と tidak boleh berisi perintah atau ajakan."]},
  {h:"なら mengambil topik lawan bicara", p:["なら unik: ia mengutip topik yang baru saja diucapkan lawan bicara lalu menanggapinya — \\"A: にほんへ いきたい。B: にほんへ いくなら、きょうとが いいです。\\" (kalau soal pergi ke Jepang, Kyoto bagus). Karena itu なら selalu terasa reaktif, bukan pembuka topik baru.", "Satu jebakan ujian: sesudah たら/ば/なら, kalimat utama boleh berisi permintaan dan ajakan; sesudah と tidak boleh. Urutan belajar yang aman: pakai たら dulu, tambahkan と untuk hukum alam, lalu なら untuk menanggapi saran — ば terakhir untuk nuansa peribahasa dan nasihat."]}
]'''))

EDITS.append(("n4-ability", '''explain:[
  {h:"Bentuk potensial: bisa", p:["Semua kata kerja bisa berubah menjadi bentuk \\"bisa\\": golongan 1 menukar vokal akhir ke baris -e lalu tambah る (かく → かける), golongan 2 menjadi られる (たべられる), golongan 3: できる dan こられる. Objeknya memakai が, bukan を: かんじが よめます. Pola panjang 〜ことが できます berarti sama tetapi lebih formal.", "Adiknya yang sering tertukar: みえる (terlihat — memang tampak) lawan みられる (bisa melihat/menonton), dan きこえる (terdengar dengan sendirinya) lawan きける (bisa mendengar). Ujian N4 senang menguji pasangan alami-vs-usaha ini."]},
  {h:"Keinginan dan saran", p:["Benda yang diinginkan memakai 〜が ほしいです dan hanya untuk diri sendiri (atau dalam pertanyaan untuk lawan bicara). Untuk orang ketiga, bahasa Jepang menambahkan tanda tampak: ほしがっています — ia menunjukkan tanda-tanda menginginkan. Kebiasaan \\"membaca tanda lahir\\" ini muncul di banyak pola emosi: こわがる, いやがる, うれしがる.", "Saran kuat memakai perbandingan masa lalu: kata kerja bentuk た + ほうが いいです (はやく ねたほうが いいです — sebaiknya tidur awal). Bentuk negatifnya memakai ないほうが いい (tidak melakukannya lebih baik). Nada ほうが いい bisa terasa menggurui, jadi kepada atasan orang Jepang melembutkannya dengan 〜たら どうですか."]}
]'''))

EDITS.append(("n4-giving", '''explain:[
  {h:"Tiga kata kerja, satu arah pandang", p:["あげる memandang dari pemberi ke luar: わたしは ともだちに ほんを あげました (saya memberi buku kepada teman). くれる membalik kamera ke penerima yang adalah \\"saya atau kubu saya\\": ともだちが （わたしに） ほんを くれました — karena penerima selalu jelas, わたしに nyaris selalu dihilangkan. もらう memandang dari penerima yang aktif menerima: せんせいに ほんを もらいました (saya menerima buku dari guru).", "Kubu \\"dalam vs luar\\" (uchi-soto) ini menentukan pilihan kata, bukan siapa yang lebih penting. Bahkan dalam keluarga: kakak memberi adik saya → くれる, karena adik termasuk kubu saya. Kesalahan memilih あげる untuk pemberian kepada diri sendiri adalah penanda klasik penutur asing."]},
  {h:"Kebaikan sebagai kata kerja", p:["Menambahkan てあげる/てくれる/てもらう pada kata kerja lain mengubahnya menjadi \\"melakukan untuk seseorang\\": おしえてあげます (saya ajari untukmu), おしえてくれます (dia mengajari saya — ada rasa terima kasih), おしえてもらいました (saya dibantu diajari). Kombinasi ini muncul terus-menerus dalam percakapan dan surat.", "Rencana juga punya dua lapis: つもりです menyatakan niat yang sudah diputuskan (らいねん いく つもりです), sedangkan ようと おもっています adalah niat yang masih dipikirkan dan belum final. Dalam negatif, つもりはありません berarti \\"tidak ada niat sama sekali\\" dan terdengar tegas — hati-hati memakainya kepada orang lain."]}
]'''))

EDITS.append(("n3-passive-causative", '''explain:[
  {h:"Pasif: kamera pindah ke yang dikenai", p:["Pasif Jepang dibuat dengan menambahkan れる/られる, dan fungsinya lebih luas daripada bahasa Indonesia. Selain pasif biasa (ほめられました, dipuji), ada pasif penderitaan khas Jepang: あめに ふられました — secara harfiah \\"saya di-hujani\\", hujan bukan pelaku yang sengaja, tetapi kerugian dirasakan subjek. Bahkan kata kerja intransitif bisa dipasifkan untuk rasa dirugikan ini: こどもに なかれました (diganggu tangisan anak).", "Pasangan を dan が juga bergeser: pasif menjaga objek tetap dengan を untuk satu pola (あしを ふまれました, kaki saya diinjak — kaki tetap milik saya yang menderita), sesuatu yang tidak ada padanannya yang rapi dalam bahasa Indonesia."]},
  {h:"Kausatif: membuat orang lain bergerak", p:["Kausatif せる/させる berarti membuat, menyuruh, atau membiarkan. Di sinilah nuansa budaya muncul: kepada atasan atau dalam laporan resmi, kausatif sering dilembutkan menjadi させていただきます (izinkan saya melakukan) agar tidak terkesan memerintah. Kausatif pasif させられる (dipaksa melakukan) menyusut dalam lisan menjadi 飲まされる, 書かされる pada golongan 1 — bentuk pendek inilah yang lebih sering Anda dengar.", "Penggunaan sehari-hari yang paling alami adalah izin dan kesempatan, bukan paksaan: こどもに すきなことを させます (membiarkan anak melakukan yang ia suka). Memahami spektrum \\"memaksa ↔ membiarkan\\" ini membuat pasif-kausatif terasa jauh kurang menakutkan."]}
]'''))

EDITS.append(("n3-obligation", '''explain:[
  {h:"Lupakan い, tambah ければ", p:["〜なければならない dibangun dari bentuk ない yang kehilangan い-nya: いかない → いかなければ なりません (harus pergi). Versi lisan memangkasnya bertahap: なきゃ, なくちゃ — bentuk yang akan Anda dengar setiap hari dalam drama dan percakapan. Semua variasi itu sah; yang berubah hanya tingkat formalitas.", "Kembarannya yang memberi napas: 〜なくても いいです (tidak melakukan pun boleh): こなくても いいです. Pasangan ini membentuk sistem izin yang lengkap bersama larangan keras 〜てはいけません dan izin santai 〜ても いいです."]},
  {h:"Terpaksa dan kewajiban sosial", p:["〜ざるを えません (terpaksa harus) adalah ujung formal dari tangga kewajiban: dipakai di berita dan dokumen saat tidak ada pilihan lain, dibangun dari bentuk klasik ざる (いかざるを えません — kecuali する yang menjadi せざるを えません).", "Tangga lengkapnya, dari ringan ke berat: 〜なくてもいい (bebas) → 〜てもいい (boleh) → 〜たほうがいい (sebaiknya) → 〜なければならない (wajib) → 〜ざるをえない (terpaksa). N3 mulai menuntut Anda memilih anak tangga yang tepat sesuai situasi sosial, bukan sekadar pola yang benar secara tata bahasa."]}
]'''))

EDITS.append(("n3-complex", '''explain:[
  {h:"ので alasan yang sopan, から alasan yang tegas", p:["ので dan から sama-sama berarti \\"karena\\", tetapi ので terdengar lebih lembut dan objektif — alasan yang menuntun kesimpulan tanpa menekan lawan bicara. Ia menempel langsung pada bentuk polos; kata benda dan kata sifat-な memakai な: しずかなので. Dalam permintaan maaf dan penjelasan di kantor, ので adalah pilihan yang aman.", "のに berada di kutub berlawanan emosinya: ia selalu membawa nada kecewa atau tidak menyangka — べんきょうしたのに おちました (sudah belajar, kok gagal juga). Karena muatan emosional ini, のに tidak dipakai untuk fakta netral; untuk kontras netral bahasa Jepang memilih が/けれど atau ても yang lebih datar."]},
  {h:"ても dan keluarga konsesi", p:["〜ても berarti \\"meskipun\\": kata kerja て + も, kata sifat-い menjadi くても, kata benda/な menjadi でも. Bentuk ini netral dan terukur: あめでも いきます — hujan pun, saya tetap berangkat, tanpa keluhan.", "Kakaknya di N3–N2: 〜くせに (padahal — nada mencela, hanya untuk orang lain), 〜わりに (untuk ukuran — hasil di luar perkiraan tarafnya), dan 〜ものの (memang benar … tetapi sulit direalisasikan). Ketiganya mewarnai konsesi dengan sikap penutur yang berbeda-beda, dan ujian membaca senang mengujinya berpasangan."]}
]'''))

EDITS.append(("n3-reported", '''explain:[
  {h:"Dua そうです yang berbeda pekerjaan", p:["そうです versi tanda (様態) menempel pada akar kata: ふりそうです (tampak akan hujan), おいしそうです (tampak enak). Penutur menilai dari bukti yang terlihat sekarang. そうです versi kabar (伝聞) menempel pada kalimat utuh: あめだそうです (katanya hujan) — penutur hanya meneruskan informasi orang lain tanpa menilai.", "Kesalahan klasik adalah mencampurnya: あめが ふるそうです bisa ditafsirkan dua arah. Dalam ujian, perhatikan apakah yang menyambung akar kata kerja/sifat atau kalimat lengkap — dari situlah maknanya ditentukan."]},
  {h:"ようです, らしい, dan tanggung jawab kata", p:["ようです menyatakan kesimpulan dari bukti tidak langsung: lantai basah, payung menetes → あめが ふったようです. Ia lebih hati-hati daripada そうです-tanda karena menyisakan ruang salah. らしい menambahkan dua rasa: tipikal (おとこらしい, jantan sebagaimana mestinya) dan kabar yang beredar (うわさによると …らしい).", "Pola kutipan 〜と いっていました (dia bilang bahwa…) dan perkiraan diri 〜と おもいます melengkapi sistem ini. Intinya, bahasa Jepang memaksa penutur menandai seberapa yakin ia pada ucapannya — kebiasaan yang membuat teks N3 terasa penuh \\"katanya\\", \\"tampaknya\\", dan \\"sepertinya\\"."]}
]'''))

EDITS.append(("n3-keigo", '''explain:[
  {h:"Dua arah hormat", p:["Keigo berjalan dua arah yang berlawanan. Sonkeigo meninggikan orang yang dibicarakan: いう → おっしゃる, みる → ごらんになる, いる/いく/くる → いらっしゃる. Kenjōgo merendahkan diri sendiri untuk mengangkat lawan bicara: いう → もうす/もうしあげます, みる → はいけんします, いく/くる → まいります.", "Pasif juga bisa bekerja sebagai penghormatan ringan: せんせいが かえられました (guru pulang — secara harfiah pasif, tetapi terasa sopan). Di tempat kerja, memilih satu anak tangga keigo yang tepat lebih penting daripada menghafal semuanya sekaligus; mulailah dari kata kerja yang paling sering Anda pakai."]},
  {h:"Konektor membangun teks", p:["Begitu kalimat bisa panjang, konektor menjadi tulangnya: しかし (namun — pembuka giliran), そのため (oleh sebab itu), また (selain itu), まず (pertama-tama), つぎに (berikutnya), さいごに (terakhir), つまり (singkatnya). Teks esai dan berita N3 tersusun dari rangka ini.", "Satu disiplin kecil: satu paragraf satu gagasan, dan konektor diletakkan di awal kalimat, bukan tengah. Dengan kerangka ini, membaca teks N3 yang panjang menjadi pekerjaan membongkar balok-balok, bukan menelan satu kalimat raksasa."]}
]'''))

EDITS.append(("n2-formal-loc", '''explain:[
  {h:"Register berita dan dokumen", p:["において menggantikan で dalam konteks formal yang abstrak — bukan hanya tempat fisik, melainkan situasi dan bidang: かいぎにおいて (dalam rapat), げんだいしゃかいに おいて (dalam masyarakat modern). Ia hampir tidak pernah dipakai dalam obrolan; kemunculannya adalah sinyal \\"teks ini resmi\\".", "に基づいて menilai sesuatu dari landasan: データに もとづいて はんだんする. Kebalikannya yang juga sering muncul adalah 〜を もとに（して） (berbekal, lebih ringan) dan 〜に したがって (mengikuti, sekaligus berarti \\"seiring\\"). Pasangan に対して punya dua wajah: kontras dua hal (あにに たいして おとうとは…) dan sasaran sikap (おきゃくさまに たいする たいど, sikap terhadap pelanggan)."]},
  {h:"Keluarga pola di/berdasarkan yang lebih luas", p:["N2 memperluas peta: における adalah versi penjelas kata benda (かいぎに おける ぎろん, perdebatan dalam rapat), につれて/にともなって menandai perubahan yang berjalan seiring (ねんれいが あがるに つれて), dan によって serba guna — oleh (pasif), dengan cara, bergantung pada, dan karena.", "Strategi membaca: lingkari pola-pola ini lebih dulu sebelum menerjemahkan isi. Pola formal justru membantu karena ia mengumumkan hubungan logis antarklausa secara terang-terangan, tidak seperti teks lisan yang mengandalkan konteks."]}
]'''))

EDITS.append(("n2-concession", '''explain:[
  {h:"Konsesi yang berat sebelah formal", p:["にもかかわらず adalah konsesi paling formal: hasil yang terjadi bertentangan dengan dugaan yang kuat. Berita sangat menyukainya karena netral dan ringkas. Bentuk lisan yang lebih ringan adalah のに; memilih にもかかわらず dalam obrolan ringan akan terdengar seperti membaca surat kabar.", "一方で menyeimbangkan dua sisi dalam satu bingkai: としが はってんする いっぽうで、かんきょうもんだいも ふえた. Jika に対して membandingkan dua hal yang diam, 一方で membandingkan dua proses yang berjalan bersamaan — perbedaan halus yang sering ditanyakan dalam soal membaca."]},
  {h:"Menumpuk argumen", p:["Tulisan argumentatif N2 dibangun berlapis: nyatakan fakta, akui sisi lawan dengan konsesi (…にもかかわらず), lalu tutup dengan posisi penulis memakai それでも/それにもかかわらず di awal kalimat berikutnya. Menguasai dua-tiga pola ini mengubah esai dari kumpulan kalimat menjadi bangunan.", "Jangan lupakan kerabatnya yang lebih sastra: それでいて (namun begitu, dengan rasa kagum) dan それなのに (namun begitu — dengan nada menyayangkan), keduanya muncul dalam bacaan panjang."]}
]'''))

EDITS.append(("n2-nominal", '''explain:[
  {h:"Empat pembungkus klausa", p:["こと membungkus fakta yang objektif dan bisa diverifikasi — dasar dari ことにする (memutuskan) dan ことになる (diputuskan/ternyata). もの membungkus hakikat dan emosi: ゆめは かなうものだ (mimpi memang untuk terwujud) dan bentuk nostalgia …したものだ (dulu sering …).", "わけ adalah kesimpulan yang ditarik dengan logika: …わけがない (tidak mungkin), …わけではない (bukan berarti), …わけにはいかない (tidak bisa, karena alasan sosial). はず adalah kepastian yang berlandas alasan kuat: くるはずです, dan lawannya はずがない. Empat kata ini terlihat seperti kata benda, padahal pekerjaannya menandai sikap penutur terhadap seluruh klausa."]},
  {h:"Kenapa N2 terasa \\"penuh nuansa\\"", p:["Perbedaan こと/もの dan わけ/はず adalah contoh sempurna lompatan N3→N2: tata bahasanya benar semua, tetapi rasa kalimatnya berubah. Ujian membaca memanfaatkan ini — dua pilihan jawaban bisa sama-sama gramatikal, dan hanya sikap penutur (yakin, meragukan, menyimpulkan) yang membedakan.", "Latihan yang efektif: ambil satu fakta dan bungkus empat cara — かれは きます. かれは くるはずです (beralasan yakin), くるわけが ありません (secara logika tidak mungkin), くるものだと おもっていました (saya kira memang begitu sifatnya), くることに なりました (sudah diputuskan ia datang)."]}
]'''))

EDITS.append(("n2-media", '''explain:[
  {h:"Kosakata abstrak Sino-Jepang", p:["Separuh kosakata N2 adalah kata majemuk dua kanji (熟語) yang bekerja seperti istilah teknis: かんきょう (lingkungan), せきにん (tanggung jawab), ひかく (perbandingan), せいさく (kebijakan). Kabar baiknya, kanji yang sudah Anda kenal bergabung membentuk kata baru — membaca on\\'yomi dengan lancar mengubah kosakata dari hafalan menjadi teka-teki yang bisa dipecahkan.", "Strateginya bukan menghafal daftar raksasa, melainkan mengenali akar kanji produktif: 化 (perubahan: こくさいか), 的 (bersifat: てっていてき), 性 (sifat: かんせい), dan 率 (rasio: わりあい). Satu akar membuka belasan kata sekaligus."]},
  {h:"Dari kata ke wacana", p:["Kosakata media jarang berdiri sendiri; ia datang berkelompok menurut topik berita: ekonomi (けいざい, ぶっか, しじょう), lingkungan (おんだんか, はいしゅつ), teknologi (じんこうちのう, じどううんてん). Belajar per tema membuat soal mendengar dan membaca jauh lebih ringan karena kata-kata itu saling memanggil.", "Modul ini memang disengaja berupa daftar inti — anggap sebagai tangga pertama. Cara menaikkannya: setiap selesai membaca contoh kalimat, buat satu kalimat tentang kampus atau kotamu memakai kosakata yang sama; kata yang pernah dipakai sendiri jauh lebih lengket daripada kata yang hanya dibaca."]}
]'''))

EDITS.append(("n2-inference", '''explain:[
  {h:"Sikap yang tidak bisa dinegosiasikan", p:["ざるをえない (dibangun dari negatif klasik ざる) menyatakan tidak ada pintu lain: いかざるを えません. Berbeda dari なければならない yang netral, pola ini selalu membawa desahan — keputusan diambil karena keadaan memaksa. Ia hidup di berita, editorial, dan keputusan resmi.", "べきだ mengukur tindakan dengan penggaris norma: やくそくは まもるべきです. Hati-hati: べきだ kepada lawan bicara bisa menggurui; orang Jepang melembutkan nasihat menjadi 〜たほうが いい atau 〜たら どうですか. Bentuk negatif べきではない terasa seperti kecaman moral."]},
  {h:"まい dan warisan bahasa klasik", p:["まい adalah negatif klasik untuk tekad dan dugaan: にどと しっぱいするまい (tidak akan gagal lagi), かれは こまい (dia mungkin tidak akan datang). Ia muncul dalam bacaan dan pidato khidmat, nyaris tidak pernah dalam obrolan. Kakaknya yang seangkatan: だろう (dugaan netral), ではあるまいか (bukankah…?), dan pola tanya retoris dalam editorial.", "Memasangkan ketiganya — ざるをえない untuk keadaan, べきだ untuk norma, まい untuk tekad/dugaan klasik — memberi Anda kendali penuh atas nada \\"terpaksa vs seharusnya\\" dalam teks formal, tema yang mendominasi bacaan N2 akhir."]}
]'''))

EDITS.append(("n1-literary", '''explain:[
  {h:"Konsesi gaya tulis tinggi", p:["といえども berarti \\"meskipun dikatakan bahwa…\\": せんもんかといえども まちがうことが ある — bahkan ahlinya pun bisa keliru. Pola ini hidup di editorial dan esai; padanan lisannya cukup というても atau …でも. Mengenali anak tangga register ini adalah inti selera bahasa N1.", "であれ dan にしても bekerja mirip dari dua titik berbeda: だれであれ (siapa pun orangnya — menegaskan tanpa kecuali), いそがしいにしても (kalaupun sibuk — mengakui syarat tetapi kewajiban tetap jalan). Keduanya menegaskan bahwa kesimpulan tidak berubah oleh pengecualian apa pun."]},
  {h:"Keluarga pola \\"sama sekali tidak berubah\\"", p:["Satu klan besar di N1 menegaskan ketidakberubahan: 〜いかんにかかわらず (tanpa memandang…), 〜はもとより (jangankan… apalagi), 〜たるもの (sebagai seorang…, tuntutan martabat profesi), dan 〜んばかりの sikap nyaris. Semua berputar pada satu poros retorika: mengangkat satu hal ke titik maksimum.", "Dalam soal membaca, pola-pola ini adalah rambu: sesudahnya hampir selalu datang kesimpulan yang tegas. Tandai mereka saat membaca cepat, karena di sanalah penulis menyimpan posisinya."]}
]'''))

EDITS.append(("n1-abstract", '''explain:[
  {h:"Idiom: kata yang maknanya melompat", p:["Kosakata N1 dibagi dua: istilah abstrak resmi (がいねん konsep, ていこう perlawanan, ぎせい pengorbanan) dan idiom tubuh/perasaan yang maknanya tidak bisa ditebak dari kanjinya — きがする (merasa), きにする (mengkhawatirkan), めがはなせない (tidak bisa lengah), あしをひっぱる (menghambat orang lain, harfiah \\"menarik kaki\\").", "Idiom tubuh sangat produktif dalam bahasa Jepang karena satu kata benda (気, 目, 手, 足) melahirkan banyak ungkapan. Belajar idiom per kata benda jangkar jauh lebih efektif daripada menghafal daftar acak: kuasai keluarga 気 (きがつく menyadari, きがあう cocok, きにいる menyukai, きになる penasaran) dan Anda membuka belasan ungkapan sekaligus."]},
  {h:"Membaca kata yang belum dikenal", p:["Pada level ini, menemui kata asing di tengah ujian adalah hal biasa — dan memang disengaja. Strateginya: urai kanjinya. 抵抗 misalnya tersusun dari 抗 (melawan) dan 抗 (menahan) — dua gagasan bertabrakan yang bersama-sama berarti perlawanan. Terjemahan kasar dari gabungan kanji ditambah konteks kalimat biasanya cukup untuk memilih jawaban.", "Jangan berhenti di satu kata tak dikenal; kalimat sesudahnya hampir selalu memparafrasekan kata sulit itu dengan bahasa yang lebih sederhana, karena penulis N1 menulis untuk pembaca yang juga sedang berpikir."]}
]'''))

EDITS.append(("n1-argument", '''explain:[
  {h:"Membalik dugaan pembaca", p:["それどころか membalik arah total: やすくなるどころか、ねあがりした — bukan turun, justru naik. Ia lebih kuat dari kalimat negasi biasa karena sekaligus mengoreksi harapan yang sempat dibangun kalimat sebelumnya. むしろ bekerja di ruang yang sama tetapi lebih tenang: ia memilih alternatif yang lebih tepat (むしろ このほうが あんぜんです).", "要するに menutup putaran argumen dengan meremasnya menjadi satu kalimat inti. Dalam soal membaca, kalimat sesudah 要するに, つまり, dan けっきょく hampir selalu merupakan jawaban dari pertanyaan \\"apa maksud penulis\\" — tandai tanpa ragu."]},
  {h:"Konektor dan posisi penulis", p:["Editorial N1 menumpuk gerakan tetap: paparkan pendapat umum (…と いわれている), balikkan (しかし/ところが), dukung dengan contoh (たとえば), dan tutup (したがって/ようするに). Pola seperti それはそうと (ngomong-ngomong, mengalihkan topik) dan まして (apalagi) memberi warna pada setiap perpindahan.", "Keahlian membaca level ini bukan lagi tata bahasa per kalimat, melainkan mengikuti ke mana penulis mengajak Anda berdiri. Konektor adalah kompasnya — dan ia selalu ditulis terang-terangan."]}
]'''))

EDITS.append(("n1-keigo-adv", '''explain:[
  {h:"Pasif sebagai penghormatan", p:["Pada tingkat resmi, pasif dipakai murni untuk meninggikan tanpa mengganti kata kerja: ぶちょうは もう おかえりになりました / ごらんになりました. Bentuk お〜になる dan ご〜になる adalah sonkeigo perifrastik yang aman untuk hampir semua kata kerja, sehingga dipakai luas dalam pengumuman dan layanan pelanggan.", "Di kutub berlawanan, させていただきます telah berkembang melebihi arti harfiahnya: dalam surat bisnis ia berfungsi sebagai peredam universal — \\"izinkan saya (dengan rendah hati) melakukan\\". Pemakaiannya yang berlebihan kadang dikritik, tetapi menghindarinya sama sekali dalam konteks resmi justru terdengar kasar."]},
  {h:"Bahasa surat resmi", p:["Surat dan surel resmi berjalan dengan frasa baku: おそれいりますが (mohon maaf mengganggu), おてすうですが (merepotkan, tetapi…), 〜を おねがい もうしあげます, penutup 〜を おまちしております. Menghafalnya sebagai balok utuh lebih berguna daripada menerjemahkan kata per kata.", "Pembedanya dari keigo N3 adalah audiens: bukan lagi lawan bicara di depan mata, melainkan institusi. Karena itu tulisan resmi menghindari subjek orang kedua dan memilih bentuk pasif serta nominalisasi — kalimat tanpa \\"Anda\\" adalah kehalusan tertinggi dalam birokrasi Jepang."]}
]'''))

EDITS.append(("n1-rhetoric", '''explain:[
  {h:"Anatomi kalimat panjang", p:["Kalimat bacaan N1 sering berupa satu rantai panjang: topik di awal, sisipan bertumpuk di tengah, dan predikat yang menentukan makna mendarat di akhir. Teknik membacanya adalah mundur dari predikat: temukan kata kerja terakhir, tanya \\"siapa melakukan apa\\", lalu baca sisipan sebagai keterangan tambahan — jangan mencoba menerjemahkan lurus dari depan.", "Penghilangan subjek (ゼロ代名詞) membuat teks terasa melompat-lompat; subjek yang hilang selalu yang paling baru disebut atau yang paling masuk akal secara alur. Menandai garis bawah pada nama/topik setiap paragraf membantu menjaga siapa yang sedang dibicarakan."]},
  {h:"Parafrase: jantung ujian N1", p:["Soal membaca N1 jarang menanyakan kata yang sama dengan teks; ia menanyakan parafrasenya. Penulis yang sama menulis もんだいは たんに おかねでは ない di teks, dan pilihan jawaban menyatakannya ulang sebagai けっして きんせんだけの もんだいではない. Melatih telinga terhadap pasangan parafrase (同義表現) adalah persiapan paling langsung.", "Pola penegasan にほかならない (tidak lain adalah) menutup banyak teks argumentatif: ia menyatakan kesimpulan penulis sebagai satu-satunya kesimpulan yang mungkin. Saat menemukannya, Anda hampir pasti sedang membaca jawaban dari pertanyaan gagasan utama."]}
]'''))

EDITS.append(("prep-sound", '''explain:[
  {h:"Lima vokal yang tidak pernah berubah", p:["Vokal Jepang a-i-u-e-o selalu dibaca sama, pendek dan jernih, tidak peduli huruf apa yang mengikutinya. Bandingkan dengan bahasa Indonesia yang vokalnya mirip — modal awal yang bagus. Yang wajib dilatih adalah vokal panjang: membedakan おばさん (bibi) dan おばあさん (nenek) atau ゆき (salju) dan ゆうき (keberanian) murni soal durasi satu ketukan lebih lama.", "Satuan ritmenya disebut mora: setiap kana tepat satu ketukan, termasuk ん dan っ kecil. Itulah mengapa にっぽん (Nippon) terasa empat ketukan (ni-p-po-n) dan mengapa lagu Jepang mudah diikuti pemula — satu nada satu kana."]},
  {h:"Suara yang sering luput", p:["っ kecil (sokuon) adalah jeda tertahan satu ketukan: きて (datang) vs きって (perangko). Dalam romaji ia ditulis sebagai konsonan ganda: kitte, zasshi, gakkō. Melewatkannya mengubah kata, jadi perlakukan ia sebagai huruf penuh, bukan hiasan.", "Bunyi ふ adalah fu yang lembut — bibir tidak menyentuh gigi seperti f bahasa Indonesia, melainkan seperti meniup lilin. Dan r Jepang berada di antara r, l, dan d: satu ketukan ujung lidah. Keduanya tidak perlu sempurna di minggu pertama; telinga yang terbiasa lebih penting daripada lidah yang sempurna."]}
]'''))

EDITS.append(("prep-hiragana", '''explain:[
  {h:"Kenapa hiragana dulu", p:["Hiragana adalah aksara pertama yang dipelajari anak Jepang, dan untuk alasan yang sama ia adalah pintu masuk terbaik: semua kata bisa ditulis dengannya, akhiran kata kerja dan partikel ditulis dengannya, dan furigana (panduan baca di atas kanji) juga memakainya. Menguasai 46 huruf dasar ini berarti Anda bisa membaca teks anak dan materi pemula secara utuh.", "Urutan belajar yang disarankan modul ini: satu baris per hari sambil menulis, bukan hanya membaca. Menulis mengaktifkan memori otot; kebanyakan orang mengingat bentuk huruf jauh lebih cepat lewat tangan daripada lewat mata."]},
  {h:"Dari 46 menjadi seratus lebih bunyi", p:["Dua titik kecil (dakuten) mengubah bunyi tak bersuara menjadi bersuara: か→が, さ→ざ, た→だ, は→ば, dan lingkaran kecil (handakuten) mengubah は→ぱ. Kombinasi kana kecil ゃゅょ membuat bunyi rangkap: きゃ (kya), しゅ (shu), ちょ (cho). Dengan tambahan ini, 46 huruf dasar membuka seluruh bunyi bahasa Jepang.", "Di Kana Trainer situs ini Anda bisa menandai kana yang sudah dikuasai satu per satu — progresnya masuk ke hitungan XP dan persen keseluruhan, jadi menandai dengan jujur membantu saran pelajaran berikutnya tetap akurat."]}
]'''))

EDITS.append(("prep-katakana", '''explain:[
  {h:"Aksara untuk kata serapan", p:["Katakana dipakai untuk kata pinjaman asing (パン roti dari Portugis, コーヒー kopi), nama asing dan asingisasi nama Anda sendiri, onomatope (ドキドキ deg-degan), serta penekanan miring ala huruf italic. Bentuknya lebih bersudut daripada hiragana karena memang dirancang terlihat \\"asing\\".", "Pasangan yang paling sering tertukar: シ (shi) vs ツ (tsu), ソ (so) vs ン (n), dan ク (ku) vs ケ (ke). Triknya perhatikan arah coretan: pada シ coretan melengkung naik dari bawah, pada ツ coretan jatuh dari atas — searah dengan cara Anda membedakan arah jatuhnya tetes air."]},
  {h:"Tanda panjang dan kata modern", p:["Dalam katakana, vokal panjang ditulis dengan garis ー (チョコレート, コーヒー), bukan menggandakan vokal seperti hiragana. Kata serapan baru terus lahir dari bahasa Inggris teknologi: スマホ (ponsel pintar), アプリ (aplikasi), リモート (kerja jarak jauh) — membaca katakana membuka separuh papan iklan dan menu di Jepang.", "Nama Anda sendiri akan ditulis dalam katakana di Jepang. Melatih menulisnya sejak modul ini membuat perkenalan diri di modul berikutnya terasa nyata, bukan sekadar latihan."]}
]'''))

EDITS.append(("prep-greetings", '''explain:[
  {h:"Salam mengikuti jam dan hubungan", p:["Salam Jepang terikat waktu: おはよう (pagi, akrab) / おはようございます (pagi, sopan), こんにちは (siang sampai sore), こんばんは (malam). Di tempat kerja, おはようございます dipakai saat pertama bertemu hari itu — bahkan jika sudah malam pada shift malam, karena maknanya bergeser menjadi \\"selamat mulai bekerja\\".", "Untuk \\"sampai jumpa\\", さようなら ternyata formal dan terasa final; percakapan sehari-hari memilih じゃあね (akrab), またあした (sampai besok), atau おつかれさま (di kantor, secara harfiah \\"terima kasih atas lelahmu\\"). Memakai salam yang tepat menurut hubungan lebih penting daripada menghafal yang paling terkenal."]},
  {h:"Perkenalan diri: pola pertama Anda", p:["Perkenalan baku berjalan tiga langkah: はじめまして (salam pembuka, harfiah \\"pertama kalinya\\"), nama + です, lalu よろしく おねがいします sebagai penutup yang meminta hubungan baik ke depan. Urutan nama mengikuti gaya Jepang dalam situasi resmi: nama keluarga dulu, baru nama pribadi.", "Frasa よろしく tidak punya padanan satu kata dalam bahasa Indonesia — ia berarti kira-kira \\"mohon kerja samanya / mohon bimbingannya\\" dan muncul di puluhan situasi. Menganggapnya sebagai \\"salam penutup serbaguna\\" akan membawa Anda jauh."]}
]'''))

EDITS.append(("prep-numbers", '''explain:[
  {h:"Sistem angka dua lapis", p:["Jepang memadukan bacaan asli dan bacaan Cina: 1–10 adalah いち, に, さん, よん/し, ご, ろく, なな/しち, はち, きゅう/く, じゅう. Beberapa angka punya dua bacaan, dan pilihan amannya: よん untuk empat (し berbunyi sama dengan \\"kematian\\"), なな untuk tujuh, きゅう untuk sembilan. Puluhan dan ratusan tinggal mengalikan: にじゅう (20), さんびゃく (300 — perhatikan perubahan bunyi ひゃく menjadi びゃく).", "Untuk harga, satuan えん ditempel di akhir: ごひゃくえん (500 yen). Dalam percakapan toko, mendengar angka dengan benar adalah keterampilan bertahan hidup pertama — latih telinga dengan menyebut harga barang di sekitar Anda."]},
  {h:"Penghitung: angka tidak pernah sendirian", p:["Menyebut jumlah benda menuntut kata bantu bilangan yang cocok dengan bentuk bendanya: ひとつ/ふたつ untuk benda umum, にん untuk orang (dengan pengecualian ひとり, ふたり), まい untuk benda tipis seperti kertas dan baju, ほん untuk benda panjang seperti botol dan pensil, さつ untuk buku, だい untuk mesin dan kendaraan. Ini ciri bahasa Jepang yang paling terasa asing di awal.", "Kabar baiknya: sistem つ umum (ひとつ, ふたつ, みっつ…) diterima hampir di semua situasi kasual sampai angka sembilan. Kuasai yang umum dulu, lalu cicil penghitung khusus menurut benda yang sering Anda temui."]}
]'''))


def main():
    src = open(PATH, encoding="utf-8").read()
    done, skipped = [], []
    for mod_id, block in EDITS:
        m = re.search(r'\{id:"' + re.escape(mod_id) + r'", title:', src)
        if not m:
            raise SystemExit("module not found: " + mod_id)
        if "explain:[" in src[m.start():m.start() + 400]:
            skipped.append(mod_id)
            continue
        local = m.start()
        v = re.search(r'vocab:\[\[', src[local:])
        v_start = local + v.start()
        close = src.index(']}', v_start)
        insert_at = close + 2
        src = src[:insert_at] + ",\n        " + block + src[insert_at:]
        done.append(mod_id)
    open(PATH, "w", encoding="utf-8").write(src)
    print("inserted:", len(done), "| skipped:", len(skipped), "| total:", len(EDITS))
    if skipped:
        print("skipped (sudah ada explain):", ", ".join(skipped))


if __name__ == "__main__":
    main()
